# Generated by Django 3.1 on 2020-08-23 13:36

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolInformation',
            fields=[
                ('schoolId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='schoolReview',
            fields=[
                ('reviewId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userRating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('userReview', models.TextField(blank=True, default='')),
                ('userPhotosURL', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('isReviewHelpful', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None)),
                ('isReviewNotHelpful', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None)),
                ('isReviewAbusive', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None)),
                ('schoolId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolinformation')),
            ],
        ),
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='schoolReviewComment',
            fields=[
                ('commentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userComment', models.TextField(blank=True, default='')),
                ('isReviewAbusive', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None)),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolreview')),
            ],
        ),
        migrations.AddField(
            model_name='schoolreview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='main.userinformation'),
        ),
        migrations.CreateModel(
            name='reviewPhoto',
            fields=[
                ('photoID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userPhotosURL', models.ImageField(blank=True, upload_to='schoolReview/')),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolinformation')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinformation')),
            ],
        ),
    ]
