# Generated by Django 3.1 on 2020-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewphoto',
            name='userPhotosURL',
            field=models.ImageField(upload_to='schoolReview/'),
        ),
    ]
