# Generated by Django 3.1 on 2020-08-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200825_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolreviewcomment',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.userinformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolreview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinformation'),
        ),
    ]
